cmd/keys.go

Normally the key will simply be shown as the key in which it was imported
```
$ lens keys show
cosmos1sxku8pkj88ctqcxyp26wzyzurxyzganr74kfqw
```
Allow the user to override the prefix to quickly encode the public key for a different chain or purpose
```
$ lens keys show --prefix osmo
osmo1sxku8pkj88ctqcxyp26wzyzurxyzganrkw9eku
```

Enable user to specify bech32 prefix

---

.gitignore
cmd/config.go

Small logic inversion in initConfig to reduce indentation and to handle some error cases (like what happens if you don't have a `$HOME/.lens` initialized
If the `$HOME/.lens` dir  doesn't exist, createConfig.
Addresses #4

Ensure a default config is present

---

cmd/keys.go

Note: Currently stacked on top of #8
lens keys enumerate will iterate over configured chains and display the addresses for each configured chain:
```
$ lens keys enumerate
keyname: default
addresses:
- chain: bitcanna
address: bcna1nueevlwxcux9xg8vdercas0eqmzwesgntyqzue
- chain: chihuahua
address: chihuahua1nueevlwxcux9xg8vdercas0eqmzwesgnjpad4f
- chain: cosmoshub
address: cosmos1nueevlwxcux9xg8vdercas0eqmzwesgn35sr5t
- chain: osmosis
address: osmo1nueevlwxcux9xg8vdercas0eqmzwesgne0rnze
```

[STACKED] lens keys enumerate

---

.github/dependabot.yml
README.md
cmd/config.go
cmd/root.go

Simple change, allows to override chain name for use in subcommands `tx`, `tendermint`, etc.
Usage:
`--chain <chain_name_in_config>`
If `--chain` is not defined, it'll default to value in config

add(config): add chain override to cli flags

---

client/query.go
cmd/distribution.go
cmd/query.go

Add standard Cosmos SDK queries for the distribution module:
```
Usage:
lens query distribution [command]
Available Commands:
commission                    query a specific validator's comission
community-pool                query things about a chain's community pool
params                        query things about a chain's distribution params
rewards                       query things about a delegator's rewards
slashes                       query things about a validator's slashes on a chain
validator-outstanding-rewards query things about a validator's (and all their delegators) outstanding rewards on a chain
```

add(dist): add distribution queries

---

.gitignore
cmd/config.go
cmd/distribution.go
cmd/root.go
cmd/tx.go

Adds an `--output` flag to _somewhat_ handle #19 . Since `output` is an item on every ChainConfig, when the flag is set it updates all of them for that current invocation.
Threw in a couple really small fixes for bugs I encountered while running the tool. This project is a great idea.

Add an output flag

---

README.md
cmd/keys.go
go.mod
go.sum

For `keys restore` command, accept mnemonic as masked input to stdin instead of a command line argument.
Resolves #37

Restore mnemonic from stdin

---

cmd/root.go
cmd/version.go

Display Lens, Cosmos SDK, and Tendermint versions
Resolves #32

Add version command

---

client/provider.go
client/query.go
client/relayer_packets.go

This PR addresses various address encoding/decoding issues, as well as outstanding calls to ibc-go and the sdk, which were causing more of the Bech32 errors that were present in the go-relayer

Kill the dreaded Bech32 errors :axe: 

---

client/chain_registry/asset_list.go
client/chain_registry/chain_info.go
client/chain_registry/chain_info_test.go
client/chain_registry/chain_registry.go
client/chain_registry/cosmos_github_registry.go
cmd/chains.go

Moving the chain-registry related code into the `client/` directory and making sure the functions/methods there are public for use in outside repos.
Closes #47

Move chain registry code into `client/` directory

---

client/chain_registry/chain_info.go
client/chain_registry/chain_info_test.go

Fixes #65
This adds handling for the additional possible endpoint formats:
1. endpoint with TLS and path e.g. `https://test.com/rpc`
2. proxied endpoint without TLS and no path e.g. `http://test.com`
3. proxied endpoint without TLS and with path e.g. `http://test.com/rpc`
Not sure why anyone would add a proxy but not add TLS (2 & 3) but hey who am I to judge ¯\_(ツ)_/¯

handle additional rpc endpoint formats

---

cmd/chains.go
go.mod
go.sum

As reported in #59, lens allows you to delete the default chain. If you delete the default chain, the tool no longer functions because it fails `validateConfig`. This means you can't re-add the default chain (or any other chain) without purging the Lens configuration file (or editing it manually). 
This PR blocks the user from deleting the default chain. If they wish to delete the default chain, they will have to first set a new default chain.

Don't allow deletion of the default chain

---

client/provider.go

The variables we use in retrys (e.g. RtyDel, RtyErr, etc.) were previously in the `provider` package in the relayer which we were importing here. Same goes for the function `MustGetHeight()`
It doesn't really make sense for them to live in the `provider` package on the relayer side so we need to add them into lens

Add variables needed in retrys

---

README.md
cmd/keys.go

Readme touchup and add keysAddCmd example

Readme Touchup

---

cmd/airdrop.go
cmd/auth.go
cmd/chains.go
cmd/config.go
cmd/crosschain.go
cmd/flags.go
cmd/keys.go
cmd/root.go
cmd/tendermint.go
cmd/version.go

- Avoid ioutil package
- Avoid directly calling os.Exit in helper function
- Use *cobra.Command object's stdout for printing (which will simplify
future tests)
- Consistently write JSON values with indentation and without HTML
escaping

Miscellaneous cleanup in cmd package

---

cmd/keys.go
cmd/keys_test.go
cmd/system_test.go
cmd/tendermint.go

I've successfully used a pattern similar to this on previous projects.
This approach allows testing the command in-process and stubbing out
stdin, stdout, and stderr.
There are some filesystem interactions, so these tests ought to be run
with t.Parallel, but right now there is a data race around some global
state in commands.
(I have another branch ready to fix those data races, after this PR is merged.)

Add initial pattern for tests in cmd package

---

cmd/airdrop.go
cmd/auth.go
cmd/authz.go
cmd/bank.go
cmd/chains.go
cmd/config.go
cmd/crosschain.go
cmd/distribution.go
cmd/flags.go
cmd/keys.go
cmd/keys_test.go
cmd/query.go
cmd/root.go
cmd/staking.go
cmd/tendermint.go
cmd/tx.go

This builds on #112 to make those tests use t.Parallel, and it
eliminates data races by passing through config instances and a single
viper instance, instead of relying on global values.

Avoid shared global state in cmd package

---

.gitignore
cmd/keys.go

Closes #9 
`lens keys enumerate` already works with a key or address as input
Just making it more clear to users.

`lens keys enumerate` uses more clear

---

client/query/bank.go
client/query/distribution.go
client/query/querier.go
client/query/query_options.go
client/query/staking.go
client/query/tendermint.go
cmd/distribution.go
cmd/query.go
cmd/staking.go
cmd/tendermint.go

Closes: #107
This PR continues the work to refactor the query logic. Implemented additional methods for some modules like distribution and tendermint methods are now part of the query (instead of just in cmd). 
This also includes improvements like hooking up flags to cmd's that didn't have them. 
This refactoring working continues but just wants to submit this work to ensure the branch doesn't diverge too much from main since now there are other people working on the project.

Refactor query, additional modules and methods

---

client/chain_registry/chain_info.go
client/chain_registry/chain_registry.go
client/chain_registry/cosmos_github_registry.go
cmd/chains.go

Creating a context.Background inside a method is generally an
anti-pattern. Instead, accept a context as an argument to the method, so
that a top-level caller can provide a meaningful root context -- in this
case, a context associated with the *cobra.Command.

Explicitly pass context to chain registry methods

---

cmd/config.go
cmd/root.go
cmd/system_test.go
cmd/tendermint_test.go

This introduces a way to inject mock RPC clients for testing commands
that expect to interact over RPC, without actually connecting to an RPC
server.

Add some tests for tendermint commands

---

client/grpc_query.go
client/query.go
client/tx.go

There were a few more context.Background calls in ChainClient that were able to be easily changed to parameters.

Use explicit context.Context parameters in ChainClient

---

client/keys.go
client/keys_test.go
cmd/keys.go

The commands for adding and restoring keys has a `--coin-type` flag which is not actually wired up to the key management methods on `ChainClient`
Closes #127

wire up the `--coin-type` flag in the key cmds

---

client/config.go
client/query.go
cmd/modules.go
go.mod
go.sum

The dependency on v2 was causing a runtime conflict with relayer's
dependency on ibc-go v3.
Tests pass locally with the update.

Update to ibc-go v3

---

client/chain_registry/chain_info.go
client/chain_registry/cosmos_github_registry.go
go.mod
go.sum

Lens was depending on the pre-modules release of go-github, so update to
the current release that uses Go modules.

Update to latest go-github release

---

README.md

I came across this repo & assumed it was not working or just a CLI, after seeing no reference to documentation or even examples, despite there being an examples repository. 
This should be in the README.

Update README with link to examples repo.

---

client/query.go
cmd/tendermint.go

Querying tx information is likely to be a desired use-case in client development when using `lens`
This PR adds functions for querying txs from the Tendermint RPC endpoint

Add functions for querying txs and wire up `QueryTx` to the cli cmd

---

client/broadcast.go

Without this, it was possible to get stuck in an infinite loop later in
BroadcastTx querying for a transaction that would never appear.

Return error when BroadcastTx has invalid sequence

---

client/tx.go

If `tx.Sign` returns an error, then we will never release a lock and will end up blocking the whole time. This piece of code ensures that we always call done which will release a lock (even if`tx.Sign` panics).
- running tests `go test -v ./...` with a success

Always calling done when signing a message

---

client/broadcast.go
client/broadcast_test.go
client/config.go
client/errors.go

Broadcasting a TX doesn't handle errors quite well. Also, the program could wait indefinitely until a TX is included and you may have no idea that something like that is even happening. That's why I've added a new config field to time out after a certain time period.
- wrote tests for this
- tested this as a part of our project at volumefi

Fix for the buggy broadcasting logic

---

client/tx.go

This PR fixes a bug in tx simulation that would present itself in testing due to how the keystore was managed. Instead of trying to read an arbitrary key to get the PubKey details we retrieve the key information for the calling chain's configured key.
There are no specific test cases in the relayer for Evmos and adding some to the relayer is probably more effort than it's worth since we will be ditching the included integration tests in favor of `ibctest`. Ideally we test EVM based chains in `ibctest` but that is outside the scope of this work.
- Checkout the relayer at https://github.com/cosmos/relayer/pull/779
- Run `make test-integration`
The tests should all run to completion and pass; before this fix you would see errors like the following
```
logger.go:130: …
```

Use configured `ChainClient` key in tx simulation

---

cmd/dynamic.go

Allow a user to specify the height at which the query is performed
```
$ ./build/lens dynamic query osmosis osmosis.gamm.v1beta1.Query Pool '{ "poolId": "678" }' --height 4741243 | jq
{
"pool": {
"@type": "/osmosis.gamm.v1beta1.Pool",
"address": "osmo10venxtvdglryxkdmvjr8wa6n3ugja40rewddlxtg0pr30vmkf47sllgslg",
"futurePoolGovernor": "24h",
"id": "678",
"poolAssets": [
{
"token": {
"denom": "ibc/D189335C6E4A68B513C10AB227BF1C1D38C746766278BA3EEB4FB14124F1D858",
"amount": "11592143478966"
},
"weight": "536870912000000"
},
{
"token": {
"denom": "uosmo",
"amount": "14754255690072"
},
"weight": "536870912000000"
}
],
"poolParams": {
"swapFee": "2000000000000000",
"exitFee": "0"
},
"totalShares": {
"denom": "gamm/pool/678",
"amount": "2938166961742364582424516"
},
"totalWeight": …
```

Allow height to be supplied to dynamic queries
